api_platform:
    title: 'Testing API Platform REST API'
    description: 'a simple test'
    version: '0.0.1'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    defaults:
        pagination_items_per_page: 30